[package]
name = "books_downloader"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "1.21.1", features = ["full"] }
tokio-util = { version = "0.7.4", features = ["compat"] }
futures = "0.3.25"
reqwest = { version = "0.11.13", features = ["json", "stream", "multipart"] }
log = "0.4"
env_logger = "0.9.0"
lazy_static = "1.4.0"
serde = { version = "1.0.144", features = ["derive"] }
serde_json = "1.0.85"
axum = "0.5.16"
translit = "0.5.0"
zip = "0.6.3"
tempfile = "3.3.0"
bytes = "1.3.0"
axum-prometheus = "0.2.0"
base64 = "0.13.0"
