[package]
name = "books_downloader"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "1.28.2", features = ["full"] }
tokio-util = { version = "0.7.8", features = ["compat"] }
futures = "0.3.28"
reqwest = { version = "0.11.18", features = ["json", "stream", "multipart"] }

tracing = "0.1.37"
tracing-subscriber = { version = "0.3.17", features = ["env-filter"]}
tower-http = { version = "0.4.3", features = ["trace"] }

once_cell = "1.18.0"

serde = { version = "1.0.163", features = ["derive"] }
serde_json = "1.0.96"
axum = "0.6.18"
translit = "0.5.0"
zip = "0.6.6"
tempfile = "3.5.0"
bytes = "1.4.0"
axum-prometheus = "0.4.0"
base64 = "0.21.2"
