[package]
name = "books_downloader"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "1.33.0", features = ["full"] }
tokio-util = { version = "0.7.10", features = ["compat"] }
futures = "0.3.29"
reqwest = { version = "0.11.22", features = ["json", "stream", "multipart"] }

tracing = "0.1.40"
tracing-subscriber = { version = "0.3.17", features = ["env-filter"]}
tower-http = { version = "0.4.4", features = ["trace"] }

once_cell = "1.18.0"

serde = { version = "1.0.192", features = ["derive"] }
serde_json = "1.0.108"
axum = "0.6.20"
translit = "0.5.0"
zip = "0.6.6"
tempfile = "3.8.1"
bytes = "1.5.0"
axum-prometheus = "0.4.0"
base64 = "0.21.5"

sentry = { version = "0.31.7", features = ["debug-images"] }
