[package]
name = "books_downloader"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "1.40.0", features = ["full"] }
tokio-util = { version = "0.7.12", features = ["compat"] }
futures = "0.3.30"
reqwest = { version = "0.12.8", features = ["json", "stream", "multipart"] }

tracing = "0.1.40"
tracing-subscriber = { version = "0.3.18", features = ["env-filter"]}
sentry-tracing = "0.34.0"
tower-http = { version = "0.6.1", features = ["trace"] }

once_cell = "1.20.1"

serde = { version = "1.0.210", features = ["derive"] }
serde_json = "1.0.128"
axum = "0.7.7"
translit = "0.5.0"
zip = "2.2.0"
tempfile = "3.13.0"
bytes = "1.7.2"
axum-prometheus = "0.7.0"
base64 = "0.22.1"

sentry = { version = "0.34.0", features = ["debug-images"] }
dotenvy = "0.15.0"
